name: Deploy Frontend to Google Cloud Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4 # Actualizado a v4

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Actualizado a v4
      with:
        node-version: '22' # Usamos la 22 como en tu PC

    - name: Install dependencies
      run: npm install

    - name: Build Angular
      run: npm run build -- --prod --base-href ./
      env:
        NODE_OPTIONS: "--openssl-legacy-provider"

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2 # Actualizado a v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Upload to Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v2 # Actualizado a v2
      with:
        path: dist/login 
        destination: masmetrica-frontend
        parent: false